## === Conect to PostgreSQL on Render ===
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## === Redis on Render ===
#spring.redis.url=${REDIS_URL}
#
## cache (prod)
#spring.cache.cache-names=categories,categoryIds
#spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=1h