spring.application.name=EasyBuy

server.port=${PORT:8080}

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/easybuy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=2000ms

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

# JWT Configuration
jwt.secret=DC2AF6C498EDB7F7C7A284322F24FD66573D2A102D19FBE07C0E0D732E30A821
jwt.accessTokenExpiration=900000
jwt.refreshTokenExpiration=604800000

# Logging
logging.level.org.springframework.security=ERROR
logging.level.com.teamchallenge.easybuy=DEBUG
logging.level.org.springframework.boot=INFO
logging.level.root=INFO

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=J.K.play2015@gmail.com
spring.mail.password=fsoq mzay upls cwcr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false

# Frontend URL
frontend.server.url=https://marketplace-easybuy-project.vercel.app

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_NAME:easybuymarketplace}
cloudinary.api-key=${CLOUD_KEY:482555657287273}
cloudinary.api-secret=${CLOUD_SECRET:3CulVI-MH7_0AcAPCAjO7yE8RlM}