## === ????????? PostgreSQL ===
#spring.datasource.url=jdbc:postgresql://localhost:5432/easybuy
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## ===  Lockal Redis (Docker) ===
#spring.redis.url=redis://localhost:6379
#
##  cache (Lockal)
#spring.cache.cache-names=categories,categoryIds
#spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=1h